name: npm-publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo 
      uses: actions/checkout@v2
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this release
        draft: false
        prerelease: false
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: ${{ github.ref }}s