name: test 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo 
      uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8' 
    - name: Cache pip on Linux
      uses: actions/cache@v1
      if: startsWith(runner.os, 'Linux')
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.python }}-${{ hashFiles('**/requirements.txt', 'setup.py') }}
        restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python }}
    - name: Install dependencies
      run: |
        pip install -U pip setuptools 
        pip install --upgrade ".[test]" -v
    - name: Run tests 
      run: |
        jupyter nbextension list
        jupyter nbextension enable --py --sys-prefix jupyter-pitaya-smoothie
        pip install jupyterlab 
        jupyter labextension list 
        jupyter labextension list 2>&1 | grep -q jupyter-pitaya-smoothie 
        jupyter labextension link